name: develop_deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: renderer
      
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: renderer

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: renderer/dist # The folder the action should deploy.
